/**
 * 
 */
package com.quick.config;

import javax.sql.DataSource;

import org.apache.commons.dbcp2.BasicDataSource;
import org.mybatis.spring.SqlSessionFactoryBean;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;

/**
 * @author U329022
 *
 */
@Configuration
@MapperScan("com.quick.dao.ibatis")
@ComponentScan({"com.quick"})
public class MyBatisConfig extends DBConfig {

	@Override
	@Bean(name="basicDataSource")
	public DataSource dataSource() {
		
		//EmbeddedDatabaseBuilder builder = new EmbeddedDatabaseBuilder();
		//DataSource ds = builder.setType(EmbeddedDatabaseType.HSQL).addScript("schema.sql").build();
        BasicDataSource basicDataSource = new BasicDataSource();
        basicDataSource.setDriverClassName(org.hsqldb.jdbcDriver.class.getName());
        basicDataSource.setUsername("sa");
        basicDataSource.setPassword("sa");
        basicDataSource.setUrl("jdbc:hsqldb:mem://localhost:9500/bookdb");
        JdbcTemplate jdbcTemplate = new JdbcTemplate(basicDataSource);
        System.out.println("Creating tables");
        jdbcTemplate.execute("drop table book if exists");
        jdbcTemplate.execute("create table book(id int generated by default as identity (start with 1) not null, title varchar(50), author varchar(50), isbn varchar(50))");
        return basicDataSource;
        
	}
	
	@Bean
    public DataSourceTransactionManager transactionManager() {
        return new DataSourceTransactionManager(dataSource());
    }
	
	@Bean(name="sqlSessionFactory")
    public SqlSessionFactoryBean sqlSessionFactory() throws Exception {
        SqlSessionFactoryBean sqlSessionFactory = new SqlSessionFactoryBean();
        sqlSessionFactory.setDataSource(dataSource());
        sqlSessionFactory.setTypeAliasesPackage("com.quick.entities");
        return sqlSessionFactory;
    }

}
